export MOD=miyoo_mini
export NDS_GCC=1
export NDS_ALSA=1

CFLAGS  += -O3
CFLAGS  += -DMIYOO_MINI
CFLAGS  += -Wl,--no-undefined

# ARM Cortex-A7 optimizations for Miyoo Mini Plus
CFLAGS  += -mfpu=neon
CFLAGS  += -ffast-math
CFLAGS  += -march=armv7-a
CFLAGS  += -mtune=cortex-a7

# Additional performance optimizations
CFLAGS  += -flto
CFLAGS  += -finline-functions
CFLAGS  += -funroll-loops
CFLAGS  += -fomit-frame-pointer

CFLAGS  += -I../inc/mini

LDFLAGS += -ljson-c
LDFLAGS += -L../lib/mini
LDFLAGS += -lssgfx
LDFLAGS += -lmi_ao
LDFLAGS += -lmi_gfx
LDFLAGS += -lmi_sys
LDFLAGS += -lshmvar
LDFLAGS += -lmi_common
 
export MORE_CFLAGS=${CFLAGS}
export MORE_LDFLAGS=${LDFLAGS}

include Makefile.base

.PHONY: scp
scp:
	scp drastic/lib/* onion@192.168.1.108:/mnt/SDCARD/Emu/drastic/lib/
